export const UIS = [
	{
		name: "Games",
		href: "/ui/games",
		url: "https://buttons.1kev.in",
		description: "App Store-like games page with animations.",
	},
	{
		name: "Buttons",
		href: "https://buttons.1kev.in",
		url: "https://buttons.1kev.in",
		description: "List of buttons with defferent states and animations.",
	},
	{
		name: "Side Nav",
		href: "https://side-nav.1kev.in",
		url: "https://side-nav.1kev.in",
		description:
			"Side navigation component built with Next.js, Tailwindcss and Framer Motion.",
	},
	// {
	//   name: "Stagger Button with Star Animation",
	//   href: "https://aka.1kev.in/ui/star-button",
	//   url: "https://aka.1kev.in/ui/star-button",
	//   description: "Button with stagger letter and star animation.",
	// },
	{
		name: "Horizontal-Vertical Nav",
		href: "https://framer-nav.1kev.in",
		url: "https://framer-nav.1kev.in",
		description:
			"Horizontal-vertical navigation component built with Next.js, Tailwindcss and Framer Motion.",
	},
	{
		name: "Animated Tabs",
		href: "https://animated-tabs.1kev.in",
		url: "https://animated-tabs.1kev.in",
		description:
			"Animated tabs component built with Remix, Tailwindcss and Framer Motion.",
	},
	{
		name: "Elastic Slider",
		href: "/ui/elastic-slider",
		url: "https://elastic-slider.1kev.in",
		description:
			"Elastic Slider component built with Next.js Radix UI and Framer Motion.",
	},
];

export const PROJECTS = [
	{
		name: "Trading Exchange",
		url: "https://exchange.1kev.in",
		description:
			"Trading exchange web app built with Next.js, Tailwindcss, Websockets Binance API.",
	},
	{
		name: "evestory",
		url: "https://evestory.day",
		description:
			"Wedding invitation web app that allows users to create and share their wedding invitation with their guests.",
	},
	{
		name: "Govesta",
		url: "https://app.govesta.id",
		description:
			"Led and orchestrated the development team to create a seamless hotel check-in system, ensuring smooth and efficient operations for guests and staff alike.",
	},
	{
		name: "Melange Radix Icons",
		url: "https://github.com/kevanantha/melange-radix-icons",
		description: "Melange bindings for Radix Icons.",
	},
	{
		name: "Snake Reason Game",
		url: "https://snake-reason-game.fly.dev/",
		description: "A simple snake game built with ReasonML and ReasonReact.",
	},
	{
		name: "eFishery Assignment",
		url: "https://fish.1kev.in/",
		description: "Assignment for eFishery recruitment process.",
	},
	{
		name: "Trillo Kanban",
		url: "https://kanban-d99f9.firebaseapp.com/",
		description: "Real-time Kanban app built with Vue and Firebase.",
	},
	{
		name: "Drumkit",
		url: "https://drumkit.1kev.in",
		description: "Drumkit app built with Javascript and HTML.",
	},
	{
		name: "Tick Tack Toe",
		url: "https://ticktacktoe.1kev.in",
		description: "Tick Tack Toe game built with React.",
	},
	{
		name: "Wedding Web Template",
		url: "https://wedding-template.1kev.in/",
		description: "A simple wedding template.",
	},
];

export const EXPERIENCES = [
	{
		company: "Mekari - Sign",
		url: "https://mekarisign.com",
		position: "Frontend Engineer",
		time: "2024 - now",
	},
	{
		company: "eFishery",
		url: "https://efishery.com",
		position: "Frontend Engineer",
		time: "2023 - 2024",
	},
	{
		company: "Mekari - Talenta",
		url: "https://www.talenta.co",
		position: "Frontend Engineer",
		time: "2021 - 2023",
	},
	{
		company: "Mekari - Platform",
		url: "http://mekari.com",
		position: "Fullstack Engineer",
		time: "2019 - 2021",
	},
	{
		company: "UrRemote",
		url: null,
		position: "Fullstack Engineer",
		time: "2018 - 2019",
	},
	{
		company: "BlueLake Indonesia",
		url: null,
		position: "Fullstack Engineer",
		time: "2018 (3 months part-time)",
	},
];

export const mockSpotifyData = {
	device: {
		id: "18466906e2fc6261b8d8582e5e732e280dc87c81",
		is_active: true,
		is_private_session: false,
		is_restricted: false,
		name: "kevan’s MacBook Pro",
		supports_volume: true,
		type: "Computer",
		volume_percent: 100,
	},
	shuffle_state: false,
	smart_shuffle: false,
	repeat_state: "off",
	timestamp: 1713032010487,
	context: {
		external_urls: {
			spotify: "https://open.spotify.com/collection/tracks",
		},
		href: "https://api.spotify.com/v1/me/tracks",
		type: "collection",
		uri: "spotify:user:kevin.anantha21:collection",
	},
	progress_ms: 7788,
	item: {
		album: {
			album_type: "album",
			artists: [
				{
					external_urls: {
						spotify: "https://open.spotify.com/artist/5INjqkS1o8h1imAzPqGZBb",
					},
					href: "https://api.spotify.com/v1/artists/5INjqkS1o8h1imAzPqGZBb",
					id: "5INjqkS1o8h1imAzPqGZBb",
					name: "Tame Impala",
					type: "artist",
					uri: "spotify:artist:5INjqkS1o8h1imAzPqGZBb",
				},
			],
			available_markets: [
				"AR",
				"AU",
				"AT",
				"BE",
				"BO",
				"BR",
				"BG",
				"CA",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DK",
				"DO",
				"DE",
				"EC",
				"EE",
				"SV",
				"FI",
				"FR",
				"GR",
				"GT",
				"HN",
				"HK",
				"HU",
				"IS",
				"IE",
				"IT",
				"LV",
				"LT",
				"LU",
				"MY",
				"MT",
				"MX",
				"NL",
				"NZ",
				"NI",
				"NO",
				"PA",
				"PY",
				"PE",
				"PH",
				"PL",
				"PT",
				"SG",
				"SK",
				"ES",
				"SE",
				"CH",
				"TW",
				"TR",
				"UY",
				"US",
				"GB",
				"AD",
				"LI",
				"MC",
				"ID",
				"JP",
				"TH",
				"VN",
				"RO",
				"IL",
				"ZA",
				"SA",
				"AE",
				"BH",
				"QA",
				"OM",
				"KW",
				"EG",
				"MA",
				"DZ",
				"TN",
				"LB",
				"JO",
				"PS",
				"IN",
				"BY",
				"KZ",
				"MD",
				"UA",
				"AL",
				"BA",
				"HR",
				"ME",
				"MK",
				"RS",
				"SI",
				"KR",
				"BD",
				"PK",
				"LK",
				"GH",
				"KE",
				"NG",
				"TZ",
				"UG",
				"AG",
				"AM",
				"BS",
				"BB",
				"BZ",
				"BT",
				"BW",
				"BF",
				"CV",
				"CW",
				"DM",
				"FJ",
				"GM",
				"GE",
				"GD",
				"GW",
				"GY",
				"HT",
				"JM",
				"KI",
				"LS",
				"LR",
				"MW",
				"MV",
				"ML",
				"MH",
				"FM",
				"NA",
				"NR",
				"NE",
				"PW",
				"PG",
				"WS",
				"SM",
				"ST",
				"SN",
				"SC",
				"SL",
				"SB",
				"KN",
				"LC",
				"VC",
				"SR",
				"TL",
				"TO",
				"TT",
				"TV",
				"VU",
				"AZ",
				"BN",
				"BI",
				"KH",
				"CM",
				"TD",
				"KM",
				"GQ",
				"SZ",
				"GA",
				"GN",
				"KG",
				"LA",
				"MO",
				"MR",
				"MN",
				"NP",
				"RW",
				"TG",
				"UZ",
				"ZW",
				"BJ",
				"MG",
				"MU",
				"MZ",
				"AO",
				"CI",
				"DJ",
				"ZM",
				"CD",
				"CG",
				"IQ",
				"LY",
				"TJ",
				"VE",
				"ET",
				"XK",
			],
			external_urls: {
				spotify: "https://open.spotify.com/album/1DNSmmRLfv97Yjq7MTFWng",
			},
			href: "https://api.spotify.com/v1/albums/1DNSmmRLfv97Yjq7MTFWng",
			id: "1DNSmmRLfv97Yjq7MTFWng",
			images: [
				{
					height: 640,
					url: "https://i.scdn.co/image/ab67616d0000b273176e82d09ac75d62810f0056",
					width: 640,
				},
				{
					height: 300,
					url: "https://i.scdn.co/image/ab67616d00001e02176e82d09ac75d62810f0056",
					width: 300,
				},
				{
					height: 64,
					url: "https://i.scdn.co/image/ab67616d00004851176e82d09ac75d62810f0056",
					width: 64,
				},
			],
			name: "InnerSpeaker",
			release_date: "2010-05-21",
			release_date_precision: "day",
			total_tracks: 11,
			type: "album",
			uri: "spotify:album:1DNSmmRLfv97Yjq7MTFWng",
		},
		artists: [
			{
				external_urls: {
					spotify: "https://open.spotify.com/artist/5INjqkS1o8h1imAzPqGZBb",
				},
				href: "https://api.spotify.com/v1/artists/5INjqkS1o8h1imAzPqGZBb",
				id: "5INjqkS1o8h1imAzPqGZBb",
				name: "Tame Impala",
				type: "artist",
				uri: "spotify:artist:5INjqkS1o8h1imAzPqGZBb",
			},
		],
		available_markets: [
			"AR",
			"AU",
			"AT",
			"BE",
			"BO",
			"BR",
			"BG",
			"CA",
			"CL",
			"CO",
			"CR",
			"CY",
			"CZ",
			"DK",
			"DO",
			"DE",
			"EC",
			"EE",
			"SV",
			"FI",
			"FR",
			"GR",
			"GT",
			"HN",
			"HK",
			"HU",
			"IS",
			"IE",
			"IT",
			"LV",
			"LT",
			"LU",
			"MY",
			"MT",
			"MX",
			"NL",
			"NZ",
			"NI",
			"NO",
			"PA",
			"PY",
			"PE",
			"PH",
			"PL",
			"PT",
			"SG",
			"SK",
			"ES",
			"SE",
			"CH",
			"TW",
			"TR",
			"UY",
			"US",
			"GB",
			"AD",
			"LI",
			"MC",
			"ID",
			"JP",
			"TH",
			"VN",
			"RO",
			"IL",
			"ZA",
			"SA",
			"AE",
			"BH",
			"QA",
			"OM",
			"KW",
			"EG",
			"MA",
			"DZ",
			"TN",
			"LB",
			"JO",
			"PS",
			"IN",
			"BY",
			"KZ",
			"MD",
			"UA",
			"AL",
			"BA",
			"HR",
			"ME",
			"MK",
			"RS",
			"SI",
			"KR",
			"BD",
			"PK",
			"LK",
			"GH",
			"KE",
			"NG",
			"TZ",
			"UG",
			"AG",
			"AM",
			"BS",
			"BB",
			"BZ",
			"BT",
			"BW",
			"BF",
			"CV",
			"CW",
			"DM",
			"FJ",
			"GM",
			"GE",
			"GD",
			"GW",
			"GY",
			"HT",
			"JM",
			"KI",
			"LS",
			"LR",
			"MW",
			"MV",
			"ML",
			"MH",
			"FM",
			"NA",
			"NR",
			"NE",
			"PW",
			"PG",
			"WS",
			"SM",
			"ST",
			"SN",
			"SC",
			"SL",
			"SB",
			"KN",
			"LC",
			"VC",
			"SR",
			"TL",
			"TO",
			"TT",
			"TV",
			"VU",
			"AZ",
			"BN",
			"BI",
			"KH",
			"CM",
			"TD",
			"KM",
			"GQ",
			"SZ",
			"GA",
			"GN",
			"KG",
			"LA",
			"MO",
			"MR",
			"MN",
			"NP",
			"RW",
			"TG",
			"UZ",
			"ZW",
			"BJ",
			"MG",
			"MU",
			"MZ",
			"AO",
			"CI",
			"DJ",
			"ZM",
			"CD",
			"CG",
			"IQ",
			"LY",
			"TJ",
			"VE",
			"ET",
			"XK",
		],
		disc_number: 1,
		duration_ms: 235866,
		explicit: false,
		external_ids: {
			isrc: "AUUM71000136",
		},
		external_urls: {
			spotify: "https://open.spotify.com/track/2a2MbiJN2skOxohykOVcss",
		},
		href: "https://api.spotify.com/v1/tracks/2a2MbiJN2skOxohykOVcss",
		id: "2a2MbiJN2skOxohykOVcss",
		is_local: false,
		name: "Solitude Is Bliss (Mickey Moonlight Reprise)",
		popularity: 58,
		preview_url:
			"https://p.scdn.co/mp3-preview/5cc2833a7c5a876fef613961f49f1bbf96e35025?cid=5111c360a24a40ae81f4ff056b915292",
		track_number: 6,
		type: "track",
		uri: "spotify:track:2a2MbiJN2skOxohykOVcss",
	},
	currently_playing_type: "track",
	actions: {
		disallows: {
			resuming: true,
			skipping_prev: true,
		},
	},
	is_playing: true,
};
